baseURL = "https://gastrofy.sk/"
languageCode = "sk-sk"
paginate = 6
theme = "portio"
title = "Gastrofy"
# Main Menu
[[menu.main]]
name = "Domov"
url = "#home"
weight = 1
[[menu.main]]
name = "O nás"
url = "#about"
weight = 2
[[menu.main]]
name = "Služby"
url = "#service"
weight = 3
# [[menu.main]]
# name = "Work"
# url = "#portfolio"
# weight = 4
[[menu.main]]
name = "Čo získate"
url = "#resume"
weight = 5
# [[menu.main]]
# name = "Blog"
# url = "#blog"
# weight = 6
[[menu.main]]
name = "Kontakt"
url = "contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "O nás"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Služby"
url = "#service"
weight = 2
[[menu.sitemap]]
name = "Čo získate"
url = "#resume"
weight = 5
[[menu.sitemap]]
name = "Kontakt"
url = "contact"
weight = 7

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Gastrofy 2021"
footerLogo = "images/contact/gastrofy-logo-widget.svg"
formspreeURL = "https://formspree.io/f/xrgrpybj"
googleAnalytics = "G-ZCQ9TMCY8Z"
logo = "images/site-navigation/gastrofy-logo.svg"

[params.address]
address = "23 Khan Niketon, Grand Street, NYK."
email = "info@gastrofy.sk"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "0950 893 610"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
